apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::579061109491:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JOT3D3EI3LFX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::579061109491:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-08-11T11:22:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1289"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: e3a53808-ad95-443c-8d28-1418b021e785
